# Межсервисный токен (мастер ⇄ агенты)
x_auth_token: "CHANGE_ME_INTER_SERVICE"

# Аккаунты для входа в UI (root имеет право менять межсервисный токен)
auth:
  accounts:
    - name: "root"
      role: "root"
      token: "ROOT_SUPER_SECRET"
    - name: "admin1"
      role: "admin"
      token: "ADMIN_SECRET"

clusters:
  "55.51":
    nodes:
      - name: "node-55.51-1"
        agent_base_url: "http://55.51:35072"
        haproxy_backend: "Jboss_client"
        haproxy_server:  "srv_55_51_1"
        jboss_service:   "jboss-eap"
  "55.52":
    nodes:
      - name: "node-55.52-1"
        agent_base_url: "http://55.52:35072"
        haproxy_backend: "Jboss_client"
        haproxy_server:  "srv_55_52_1"
        jboss_service:   "jboss-eap"
  "55.146":
    nodes:
      - name: "node-55.146-1"
        agent_base_url: "http://55.146:35072"
        haproxy_backend: "Jboss_client"
        haproxy_server:  "srv_55_146_1"
        jboss_service:   "jboss-eap"
  "55.147":
    nodes:
      - name: "node-55.147-1"
        agent_base_url: "http://55.147:35072"
        haproxy_backend: "Jboss_client"
        haproxy_server:  "srv_55_147_1"
        jboss_service:   "jboss-eap"
