x_auth_token: "CHANGE_ME_INTER_SERVICE"   # должен совпадать с мастером
base_dir: "/tmp/pattern_controller"

haproxy_runtime_socket: "/run/haproxy/admin.sock"
haproxy_cfg_path: "/etc/haproxy/haproxy.cfg"
sync_cfg_reload: false

# jboss_health:
#   tcp_port: 8080
#   http_url: "http://127.0.0.1:9990/health"
